### ISSUE TITLE
How to run test and organize the downloaded files?

### ISSUE THREAD

**Issue by linlinge** [sitzikbs/Nesti-Net#4]

**Comment by linlinge** [comment]
When I try to test the project with your upload models, it gives the following error. I was confused about the file organization structure of this project. Where should I unzip the downloaded file?
![image](https://user-images.githubusercontent.com/26290410/93771247-d4bd1980-fc4f-11ea-8d01-18c5d9bc4707.png)

**Comment by sitzikbs** [comment]
I think it has something to do with your version of python. 

Google searching the error: 
To get rid of this Error: “ 'dict' object has no attribute 'iteritems' ” if you are using python3, you can use the dict.items() function instead of dict.iteritems().

The dict.iteritems() is removed in python3.

The provided zip files are meant to all be unzipped in the same dir.
